services:
  - type: web
    name: pepe-backend
    runtime: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: CLERK_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: pepe-prod-db
          property: connectionString

databases:
  - name: pepe-prod-db
    databaseName: pepe_prod_db
    user: pepe_prod_db_user
    region: frankfurt
